# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
#  - osx
julia:
  - 0.5.0-rc0
  - 0.4.6
notifications:
  email: false
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Gillespie"); Pkg.test("Gillespie"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Gillespie")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter"); Pkg.add("Gadfly"); using Documenter; using Gadfly;'
  - julia -e 'cd(Pkg.dir("Gillespie")); include(joinpath("docs", "make.jl"))'
